from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from . import views
# API root view
@api_view(['GET'])
def api_root(request, format=None):
    return Response({
        'register': reverse('register', request=request, format=format),
        'login': reverse('api_token_auth', request=request, format=format),
        'modules': reverse('module-list', request=request, format=format),
        'professors': reverse('professor-list', request=request, format=format),
        'ratings': reverse('rating-list', request=request, format=format)
    })

# Create a new router instance
router = DefaultRouter()

# Register viewsets
router.register(r'module-instances', views.ModuleInstanceViewSet)
router.register(r'professors', views.ProfessorViewSet)
router.register(r'ratings', views.RatingViewSet, basename='rating')
router.register(r'modules', views.ModuleViewSet)

urlpatterns = [
    # Include all routes generated by the router
    path('', api_root, name='api-root'),
    path('', include(router.urls)),
]